server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/expanse_tracker
    username: postgres
    password: anuj123
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
              - Path=/auth/**

        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/expenses/**
          filters:
            - AuthenticationFilter

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service  # Modify based on your authentication provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
