server:
  port: 8080

jwt:
  secret: secret123

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://postgres:5432/expanse_tracker
    username: postgres
    password: anuj123
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/expense-service/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
